name: ci-cd
on:
  push:
  pull_request:
  release:
    types:
      - 'published'
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn test:lint

      - name: Unit Tests
        run: yarn test:unit --coverage

      - name: Build
        run: yarn test:build

      - uses: codecov/codecov-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info

  build_and_deploy:
    runs-on: ubuntu-latest
    needs:
      - code_quality
    if: github.event_name == 'release'
    steps:
      - name: Install
        run: yarn install

      - name: Build
        run: yarn test:build

      - name: Deploy
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
